AllCops:
  Exclude:
    - bin/**/*
    - tasks/**/*
  TargetRubyVersion: 2.4
Metrics/MethodLength:
  Max: 30
  CountComments: false
Metrics/AbcSize:
  Exclude:
    - spec/**/*
    - perf/**/*
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Exclude: 
    - spec/**/*
    - perf/**/*
Metrics/LineLength:
  Exclude:
    - spec/**/*
    - perf/**/*
Style/FrozenStringLiteralComment:
  EnforcedStyle: always