AllCops:
  TargetRubyVersion: 2.4
Metrics/MethodLength:
  Max: 25
  CountComments: false
Metrics/AbcSize:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*
Style/FrozenStringLiteralComment:
  EnforcedStyle: always